<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Commons\Model.csproj" />
    <ProjectReference Include="..\Model\Repositories.csproj" />
    <ProjectReference Include="..\Patterns\Logic.csproj" />
  </ItemGroup>

</Project>